### ISSUE TITLE
trouble installing git

### ISSUE THREAD

**Issue by travisjguy** [r-bio/logistics#14]
I have a macpro Os X 10.9.5

and I get the message

Unsafe app detected

Your security preferences allow installation of only apps from the Mac App Store and identified developers.

“git-2.2.1-intel-universal-mavericks.pkg” is on the disk image “git-2.2.1-intel-universal-mavericks.dmg”. Google Chrome.app downloaded this disk image today at 11:03 AM from sourceforge.net.

Your security preferences allow installation of only apps from the Mac App Store and identified developers.

“git-2.2.1-intel-universal-mavericks.pkg” is on the disk image “git-2.2.1-intel-universal-mavericks.dmg”. Google Chrome.app downloaded this disk image today at 11:03 AM from sourceforge.net.

**Comment by fmichonneau** [comment]
Could you please type in your terminal

`which git`

and let me know of the output?

With 10.9 you might not need to install it.

  Thanks!

**Comment by travisjguy** [comment]
Last login: Thu Feb  5 10:41:56 on console
traviss-mbp:~ Tguy$ which git
/usr/bin/git
traviss-mbp:~ Tguy$

**Comment by fmichonneau** [comment]
OK, you're good to go. No need to install git again.

**Comment by travisjguy** [comment]
cool!!  Thanks!
